apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ .Values.namespace }}"
  name: {{ include "vote-app.fullname" . }}
  labels:
    {{- include "vote-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vote-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vote-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.readypath }}
              port: {{ .Values.readyport }}
            initialDelaySeconds: 5
            periodSeconds: 10