apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-getting-started-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      myComponent: k8s.tutorial
  template:
    metadata:
      labels:
        myComponent: k8s.tutorial
    spec:
      containers:
      - name: docker-getting-started-container
        image: docker/getting-started
        ports:
        - containerPort: 80
---
apiVersion: v1
Kind: Service
metadata:
  name: docker-getting-started-deployment
