apiVersion: v1
kind: Service
metadata:
  name: k8s-tutorial
  labels:
    run: k8s-tutorial
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30037
      protocol: TCP
      name: http
  selector:
    run: k8s-tutorial
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tutorial
spec:
  selector:
    matchLabels:
      run: k8s-tutorial
  template:
    metadata:
      labels:
        run: k8s-tutorial
    spec:
      containers:
        - name: k8s-tutorial
          image: docker/getting-started
          ports:
            - containerPort: 80
